services:
  - type: web
    name: ulinzi-project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
